# Generated by Django 4.2.11 on 2025-11-18 15:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('data_file', models.FileField(upload_to='datasets/')),
                ('total_records', models.PositiveIntegerField(default=0)),
                ('avg_flowrate', models.FloatField(blank=True, null=True)),
                ('avg_pressure', models.FloatField(blank=True, null=True)),
                ('avg_temperature', models.FloatField(blank=True, null=True)),
                ('type_distribution', models.JSONField(blank=True, default=dict)),
                ('summary_pdf', models.FileField(blank=True, null=True, upload_to='reports/')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
